attention_classes: [table, zone, people, robot]

table_instances: [barra, table_default]
zone_instances: [waiting_zone, zone_default]
person_instances: [person_default]
robot_instances: [robot_default]

barra: ["0.0, 0.0, 0.75"]

table_default: ["0.5, 0.15, 0.75",
                "0.5, -0.15, 0.75",
                "0.0, 0.15, 0.75",
                "0.0, -0.15, 0.75",
                "-0.5, 0.15, 0.75",
                "-0.5, -0.15, 0.75",
                "0.4, 0.6, 1.00",
                "0.4, -0.6, 1.00",
                "-0.4, 0.6, 1.00",
                "-0.4, -0.6, 1.00"
                ]

waiting_zone: ["1.0, 1.0, 1.0",
               "1.0, -1.0, 1.0",
               "-1.0, 1.0, 1.0",
               "-1.0, -1.0, 1.0"
              ]
zone_default: ["1.0, 1.0, 1.0",
               "1.0, -1.0, 1.0",
               "-1.0, 1.0, 1.0",
               "-1.0, -1.0, 1.0"
              ]
person_default: ["2.0, 0.0, 1.8", "2.0, 0.0, 1.8"]
robot_default: ["2.0, 1.0, 1.2", "2.0, 0.0, 1.2", "2.0, -1.0, 1.2"]
