attention_classes: [table, zone, person, robot]

table_instances: [bar, table_default]
zone_instances: [waiting_zone, zone_default]
person_instances: [person_default]
robot_instances: [robot_default]

bar: ["-0.5, 0.0, 0.75", "0.0, 0.0, 0.75", "0.5, 0.0, 0.75"]

table_default: ["0.0, 0.0, 0.75",
                "0.5, 0.0, 1.0",
                "-0.5, 0.0, 1.0",
                "0.0, 0.5, 1.0",
                "0.0, -0.5, 1.0"
                ]

waiting_zone: ["1.0, 1.0, 1.0",
               "1.0, -1.0, 1.0",
               "-1.0, 1.0, 1.0",
               "-1.0, -1.0, 1.0"
              ]
zone_default: ["1.0, 1.0, 1.0",
               "1.0, -1.0, 1.0",
               "-1.0, 1.0, 1.0",
               "-1.0, -1.0, 1.0"
              ]
person_default: ["0.0, 0.0, 0.0"]
robot_default: ["2.0, 1.0, 1.2", "2.0, 0.0, 1.2", "2.0, -1.0, 1.2"]
