attention_classes: [table, zone]

table_instances: [barra, table_default]
zone_instances: [waiting_zone, zone_default]

barra: ["0.0, 0.0, 0.75"]

table_default: ["0.5, 0.15, 0.75",
                "0.5, -0.15, 0.75",
                "0.0, 0.15, 0.75",
                "0.0, -0.15, 0.75",
                "-0.5, 0.15, 0.75",
                "-0.5, -0.15, 0.75",
                "0.4, 0.6, 1.00",
                "0.4, -0.6, 1.00",
                "-0.4, 0.6, 1.00",
                "-0.4, -0.6, 1.00"
                ]

waiting_zone: ["1.0, 1.0, 1.0",
               "1.0, -1.0, 1.0",
               "-1.0, 1.0, 1.0",
               "-1.0, -1.0, 1.0"
              ]
zone_default: ["1.0, 1.0, 1.0",
               "1.0, -1.0, 1.0",
               "-1.0, 1.0, 1.0",
               "-1.0, -1.0, 1.0"
              ]
