(robot_at_home ?r - robot)
(table_checked ?t - table)
(order_ready ?t - table)
(order_to_barman ?r - robot)
(wp_bar_location ?l - waypoint)
(wp_entry_location ?l - waypoint)
(barman ?p - person)
(order_checked ?r - robot)
(order_needs_fix ?r - robot)
(order_fixed ?r - robot)
(order_delivered ?t - table)
(is_wp_near_table ?wp - waypoint ?t - table)
(is_table_at ?t - table ?r - room)
(new_customer_attended ?p - person ?t - table)
(wp_in_zone ?wp - waypoint ?z - zone)
(person_detected ?r -robot ?p - person ?z - zone)
(attended_person ?p - person ?t - table ?z - zone)
(robot_at_zone ?r - robot ?z - zone)
(zone_at_room ?z - zone ?r - room)
